const portfolioData = [
  {
    particulars: "HDFC Bank",
    symbol: "HDFCBANK",
    purchasePrice: 1490,
    quantity: 50,
    exchange: "NSE",
    sector: "Financial",
  },
  {
    particulars: "Bajaj Finance",
    symbol: "BAJFINANCE",
    purchasePrice: 6466,
    quantity: 15,
    exchange: "NSE",
    sector: "Financial",
  },
  {
    particulars: "ICICI Bank",
    symbol: "ICICIBANK",
    purchasePrice: 780,
    quantity: 84,
    exchange: "NSE",
    sector: "Financial",
  },
  {
    particulars: "Bajaj Housing",
    symbol: "BAJAJHFL",
    purchasePrice: 130,
    quantity: 504,
    exchange: "NSE",
    sector: "Financial",
  },
  {
    particulars: "Savani Financials",
    symbol: "SAVFI",
    purchasePrice: 24,
    quantity: 1080,
    exchange: "BSE",
    sector: "Financial",
  },
  {
    particulars: "Affle India",
    symbol: "AFFLE",
    purchasePrice: 1151,
    quantity: 50,
    exchange: "NSE",
    sector: "Tech",
  },
  {
    particulars: "LTI Mindtree",
    symbol: "LTIM",
    purchasePrice: 4775,
    quantity: 16,
    exchange: "NSE",
    sector: "Tech",
  },
  {
    particulars: "KPIT Tech",
    symbol: "KPITTECH",
    purchasePrice: 672,
    quantity: 61,
    exchange: "NSE",
    sector: "Tech",
  },
  {
    particulars: "Tata Tech",
    symbol: "TATATECH",
    purchasePrice: 1072,
    quantity: 63,
    exchange: "NSE",
    sector: "Tech",
  },
  {
    particulars: "BLS E-Services",
    symbol: "BLSE",
    purchasePrice: 232,
    quantity: 191,
    exchange: "NSE",
    sector: "Tech",
  },
  {
    particulars: "Tanla",
    symbol: "TANLA",
    purchasePrice: 1134,
    quantity: 45,
    exchange: "BSE",
    sector: "Tech",
  },
  {
    particulars: "Dmart",
    symbol: "DMART",
    purchasePrice: 3777,
    quantity: 27,
    exchange: "NSE",
    sector: "Consumer",
  },
  {
    particulars: "Tata Consumer",
    symbol: "TATACONSUM",
    purchasePrice: 845,
    quantity: 90,
    exchange: "NSE",
    sector: "Consumer",
  },
  {
    particulars: "Pidilite",
    symbol: "PIDILITIND",
    purchasePrice: 2376,
    quantity: 36,
    exchange: "NSE",
    sector: "Consumer",
  },
  {
    particulars: "Tata Power",
    symbol: "TATAPOWER",
    purchasePrice: 224,
    quantity: 225,
    exchange: "NSE",
    sector: "Power",
  },
  {
    particulars: "KPI Green",
    symbol: "KPIGREEN",
    purchasePrice: 875,
    quantity: 50,
    exchange: "NSE",
    sector: "Power",
  },
  {
    particulars: "Suzlon",
    symbol: "SUZLON",
    purchasePrice: 44,
    quantity: 450,
    exchange: "NSE",
    sector: "Power",
  },
  {
    particulars: "Gensol",
    symbol: "GENSOL",
    purchasePrice: 998,
    quantity: 45,
    exchange: "NSE",
    sector: "Power",
  },
  {
    particulars: "Hariom Pipes",
    symbol: "HARIOMPIPE",
    purchasePrice: 580,
    quantity: 60,
    exchange: "NSE",
    sector: "Pipe",
  },
  {
    particulars: "Astral",
    symbol: "ASTRAL",
    purchasePrice: 1517,
    quantity: 56,
    exchange: "NSE",
    sector: "Pipe",
  },
  {
    particulars: "Polycab",
    symbol: "POLYCAB",
    purchasePrice: 2818,
    quantity: 28,
    exchange: "NSE",
    sector: "Pipe",
  },
  {
    particulars: "Clean Science",
    symbol: "CLEAN",
    purchasePrice: 1610,
    quantity: 32,
    exchange: "NSE",
    sector: "Others",
  },
  {
    particulars: "Deepak Nitrite",
    symbol: "DEEPAKNTR",
    purchasePrice: 2248,
    quantity: 27,
    exchange: "NSE",
    sector: "Others",
  },
  {
    particulars: "Fine Organic",
    symbol: "FINEORG",
    purchasePrice: 4284,
    quantity: 16,
    exchange: "NSE",
    sector: "Others",
  },
  {
    particulars: "Gravita",
    symbol: "GRAVITA",
    purchasePrice: 2037,
    quantity: 8,
    exchange: "NSE",
    sector: "Others",
  },
  {
    particulars: "SBI Life",
    symbol: "SBILIFE",
    purchasePrice: 1197,
    quantity: 49,
    exchange: "NSE",
    sector: "Others",
  },
];

module.exports = portfolioData;
