// Mock portfolio data for demonstration
// In a real application, this would be stored in a database
// The CMP values here are used as the baseline; they update via the API

import type { Stock } from "./types"

export const mockPortfolioData: Stock[] = [
  {
    id: "1",
    name: "Infosys",
    symbol: "INFY",
    sector: "Technology",
    exchange: "NSE",
    purchasePrice: 1500,
    quantity: 10,
    cmp: 1850,
    peRatio: 22.5,
    latestEarnings: 125.5,
    lastUpdated: Date.now(),
  },
  {
    id: "2",
    name: "HDFC Bank",
    symbol: "HDFCBANK",
    sector: "Financials",
    exchange: "NSE",
    purchasePrice: 1200,
    quantity: 20,
    cmp: 1580,
    peRatio: 18.3,
    latestEarnings: 95.2,
    lastUpdated: Date.now(),
  },
  {
    id: "3",
    name: "TCS",
    symbol: "TCS",
    sector: "Technology",
    exchange: "NSE",
    purchasePrice: 3500,
    quantity: 5,
    cmp: 4200,
    peRatio: 28.1,
    latestEarnings: 205.75,
    lastUpdated: Date.now(),
  },
  {
    id: "4",
    name: "Reliance",
    symbol: "RELIANCE",
    sector: "Energy",
    exchange: "NSE",
    purchasePrice: 2400,
    quantity: 15,
    cmp: 2950,
    peRatio: 15.8,
    latestEarnings: 185.1,
    lastUpdated: Date.now(),
  },
  {
    id: "5",
    name: "ITC",
    symbol: "ITC",
    sector: "Consumer Goods",
    exchange: "NSE",
    purchasePrice: 280,
    quantity: 50,
    cmp: 420,
    peRatio: 12.5,
    latestEarnings: 35.5,
    lastUpdated: Date.now(),
  },
  {
    id: "6",
    name: "Axis Bank",
    symbol: "AXISBANK",
    sector: "Financials",
    exchange: "NSE",
    purchasePrice: 850,
    quantity: 25,
    cmp: 1120,
    peRatio: 16.2,
    latestEarnings: 68.9,
    lastUpdated: Date.now(),
  },
]
